### PR TITLE
Add Multilanguage Support

### PR DESCRIPTION
**Pull request by ski7777**
From now on you can easily access translation files to easily use apps with multiple languages. A good App to set the language will follow.

Raphael

### CODE REVIEW

**Comment by harbaum** [comment]
The operating system already includes an internationalization system and most applications and frameworks are already prepared to use it. There's no need to re-invent the wheel. Actually doing so would make things very complex in the end.

Please google e.g. for "pyqt internationalisation" and "linux locale settings"

**Comment by harbaum** [comment]
What's the "confused smiley" supposed to mean? If you think your solution is better, then please give it a go. But please try to get the whole setup working before committing parts of it. That way you can be sure that your approach will actually work and that we won't have to remove the code again.

**Comment by ski7777** [comment]
Currently the Setup is working on my TXT. Next I will relese a Settings in which I prefer to integrate things like Wifi, updates, ...
I hope we can use the whole System from v0.9.3 on.

Raphael

P.S. I think the pyqt internationalisation would be an overkill and linux locale settings will not work on our read-only system.

**Comment by rkunze** [comment]
> P.S. I think the pyqt internationalisation would be an overkill 

Support for pyqt internationalisation is present anyway, because it is built into pyqt. I don't see the need to introduce a homegrown i18n system if we already have a ready-made one.

> and linux locale settings will not work on our read-only system.

Locale settings are environment variables - this has nothing to do with the system files being read-only or not. Additionally, configuration settings in `/etc` _are_ writeable even in the simple layout, the settings will be stored in the config dir on the FAT partition.

**Comment by ski7777** [comment]
Currently I am working on an app which combines Netinfo, Wlan and a new Update feature. I am calling it "Settings". Additionally I put a small feature to set the system language.
The app is fully translated in English and German with my translation solution. I don't need an extra tool tool to translate something. I need an editor and that's all.
I would like to put the app into 0.9.3. So if you say, that you will not push my solution, I will put it into my apps directly.

Raphael

P.s.: To update the files om the sd card, I need to know, whether the ftc user has a password. Currently I say, that the user should unset the password fir the update process. But I would prefer to ask the user for the password, if it's set.

P.P.s.: I will implement a feature too, which can change/set/unset a password for the user ftc and root. But I think normal users will not set any passwords, so I will implement it later. Can I make the characters invisible like in every password confirmation?

**Comment by ski7777** [comment]
Currently I am working on an app which combines Netinfo, Wlan and a new Update feature. I am calling it "Settings". Additionally I put a small feature to set the system language.
The app is fully translated in English and German with my translation solution. I don't need an extra tool tool to translate something. I need an editor and that's all.
I would like to put the app into 0.9.3. So if you say, that you will not push my solution, I will put it into my apps directly.

Raphael

P.s.: To update the files om the sd card, I need to know, whether the ftc user has a password. Currently I say, that the user should unset the password fir the update process. But I would prefer to ask the user for the password, if it's set.

P.P.s.: I will implement a feature too, which can change/set/unset a password for the user ftc and root. But I think normal users will not set any passwords, so I will implement it later. Can I make the characters invisible like in every password confirmation?

**Comment by ski7777** [comment]
Currently I am working on an app which combines Netinfo, Wlan and a new Update feature. I am calling it "Settings". Additionally I put a small feature to set the system language.
The app is fully translated in English and German with my translation solution. I don't need an extra tool tool to translate something. I need an editor and that's all.
I would like to put the app into 0.9.3. So if you say, that you will not push my solution, I will put it into my apps directly.

Raphael

P.s.: To update the files om the sd card, I need to know, whether the ftc user has a password. Currently I say, that the user should unset the password fir the update process. But I would prefer to ask the user for the password, if it's set.

P.P.s.: I will implement a feature too, which can change/set/unset a password for the user ftc and root. But I think normal users will not set any passwords, so I will implement it later. Can I make the characters invisible like in every password confirmation?

**Comment by harbaum** [comment]
> So if you say, that you will not push my solution, I will put it into my apps directly.

Please do that in your personal branches and not in any of the main repositories. Implementing a custom i18n system in some applications while using the system provided mechanisms in others will cause significant confusion.

Also please don't release programs that simply duplicate other programs functionality. This will also confuse users. 

Please, let's keep things clean and simple.

**Comment by ski7777** [comment]
What should I learn from my triple post and double opening yesterday? Move the android github app to trash!

I don't think, that we should use different translation systems. In my opinion we should use the easiest system for both developer and translator.

My System is based very simple you only need the base class, which is currently in my TouchStyle Pull:
`class Language():
    def **init**(self, path, default_language):
        self.path = path
        self.default_language = default_language
        try:
            config = configparser.RawConfigParser()
            config.read(CONFIG_FILE)
            self.language = config.get('general', 'language')
        except:
            self.language = self.default_language

```
    try:
        self.global_error = False
        self.translation = configparser.RawConfigParser()
        self.translation.read(self.path)
    except:
        self.global_error = True

def get_string(self, key):
    if self.global_error == False:
        try:
            return(self.translation.get(self.language, key))
        except:
            pass

        try:
            return(self.translation.get(self.default_language, key))
        except:
            pass
    return('missingno')`
```

 Then I need a confug file at /media/sdcard/data/config.conf:
`[general]
language: DE`
and a translation file e.g. in the app-directory. "translation":
`[EN]
hello: Hello World
[DE]
hello: Hallo Welt
[FR]
hello: Salut le monde`

The last thing I need is the app itself:
`from TouchStyle import *
translation = Language('path_to_app/translation', 'EN')
print(translation.get_string('hello'))`

If German is your user language you will be welcomed in German, if English it will be English and French to French. All the others will be English.

How do another system work? Could we imprive mine?

Raphael

**Comment by ski7777** [comment]
App is finished. I will open a pull request in the [TXT](https://github.com/ftCommunity/ftcommunity-TXT) repository. If anybody can show me a better way to translate the app, you are welcome to say it and then I will implement it.

Raphael

**Comment by ski7777** [comment]
I am afraid that nobody will share his idea

Raphael

**Pull request closed without merging**
